# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    main_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

main_controller:
  ros__parameters:
    joints:
      - shoulder
      - elbow
      - wrist
      - wristr
      - torso
    command_interfaces:
      - position
    state_interfaces:
      - position